"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["timer.py"]
OPTIONS = {
    "iconfile": "timer.icns",
}

setup(
    name="Timer",
    app=APP,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
